# Generated by Django 5.2.7 on 2025-10-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('hero_class', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Heroes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['hero_class'], name='heroes_hero_hero_cl_345489_idx'), models.Index(fields=['name'], name='heroes_hero_name_2f7a12_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('slug', ''), _negated=True), name='hero_slug_not_empty')],
            },
        ),
    ]
