# Generated by Django 5.2.7 on 2025-10-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='hero_pic',
            field=models.ImageField(blank=True, null=True, upload_to='hero_pictures/'),
        ),
    ]
