# Generated by Django 5.2.7 on 2025-10-24 17:33

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0003_remove_hero_heroes_hero_hero_cl_345489_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hero',
            name='hero_slug_not_empty',
        ),
        migrations.RemoveIndex(
            model_name='hero',
            name='heroes_hero_name_2f7a12_idx',
        ),
        migrations.AlterField(
            model_name='hero',
            name='secondary_class',
            field=models.CharField(blank=True, choices=[('TANK', 'Tank'), ('FIGHTER', 'Fighter'), ('ASSASSIN', 'Assassin'), ('MAGE', 'Mage'), ('MARKSMAN', 'Marksman'), ('SUPPORT', 'Support')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='hero',
            constraint=models.CheckConstraint(condition=models.Q(('slug', ''), _negated=True), name='hero_slug_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='hero',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_hero_name_ci_unique'),
        ),
    ]
