# Generated by Django 5.2.7 on 2025-10-15 17:18

import django.core.validators
import django.db.models.constraints
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ign', models.CharField(max_length=24, unique=True, validators=[django.core.validators.RegexValidator(message='In-Game Name must be 2-24 characters long and can include letters, numbers, underscores, hyphens, and periods.', regex='^[A-Za-z0-9_.\\-]{2,24}$'), django.core.validators.MinLengthValidator(2)])),
                ('real_name', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('GOLD', 'Gold Lane'), ('MID', 'Mid Lane'), ('JUNGLE', 'Jungle'), ('EXP', 'Exp Lane'), ('ROAM', 'Roam')], db_index=True, max_length=10)),
                ('nationality', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code', max_length=2)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the player is currently active')),
                ('achievements', models.TextField(blank=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='teams.team')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['-is_active', 'team__name', 'role', 'ign'],
                'indexes': [models.Index(fields=['team', 'role'], name='players_pla_team_id_125752_idx'), models.Index(fields=['team', 'is_active'], name='players_pla_team_id_1a80c1_idx'), models.Index(fields=['ign'], name='players_pla_ign_72ab0a_idx')],
                'constraints': [models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('team', 'ign'), name='unique_team_ign')],
            },
        ),
    ]
