# Generated by Django 5.2.7 on 2025-10-19 04:42

import django.db.models.deletion
import apps.players.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_name_player_profile_picture_player_slug'),
        ('teams', '0003_alter_team_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_at_team', models.CharField(choices=[('GOLD', 'Gold Lane'), ('MID', 'Mid Lane'), ('JUNGLE', 'Jungle'), ('EXP', 'Exp Lane'), ('ROAM', 'Roam')], db_index=True, max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if currently active with the team', null=True)),
                ('is_starter', models.BooleanField(default=False, help_text='Indicates if the player was a starter during this membership')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['ign']},
        ),
        migrations.RemoveConstraint(
            model_name='player',
            name='unique_team_ign',
        ),
        migrations.RemoveIndex(
            model_name='player',
            name='players_pla_team_id_125752_idx',
        ),
        migrations.RemoveIndex(
            model_name='player',
            name='players_pla_team_id_1a80c1_idx',
        ),
        migrations.RemoveField(
            model_name='player',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AddField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='facebook',
            field=models.URLField(blank=True, help_text="Link to player's Facebook profile"),
        ),
        migrations.AddField(
            model_name='player',
            name='instagram',
            field=models.URLField(blank=True, help_text="Link to player's Instagram profile"),
        ),
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.players.models.player_photo_upload_to),
        ),
        migrations.AddField(
            model_name='player',
            name='x',
            field=models.URLField(blank=True, help_text="Link to player's X (formerly Twitter) profile"),
        ),
        migrations.AddField(
            model_name='player',
            name='youtube',
            field=models.URLField(blank=True, help_text="Link to player's YouTube channel"),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['role', 'is_active'], name='players_pla_role_7bef0a_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['nationality'], name='players_pla_nationa_103a64_idx'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.CheckConstraint(condition=models.Q(('slug', ''), _negated=True), name='player_slug_not_empty'),
        ),
        migrations.AddField(
            model_name='playermembership',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='players.player'),
        ),
        migrations.AddField(
            model_name='playermembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='teams.team'),
        ),
        migrations.AddIndex(
            model_name='playermembership',
            index=models.Index(fields=['team', 'start_date'], name='players_pla_team_id_28cd31_idx'),
        ),
        migrations.AddIndex(
            model_name='playermembership',
            index=models.Index(fields=['player', 'start_date'], name='players_pla_player__567550_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playermembership',
            unique_together={('player', 'team', 'start_date')},
        ),
    ]
