# Generated by Django 5.2.7 on 2025-10-19 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_playermembership_alter_player_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='real_name',
        ),
    ]
