# Generated by Django 5.2.7 on 2025-10-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_remove_player_real_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ign',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
