# Generated by Django 5.2.7 on 2025-10-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_alter_player_ign'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='player',
            name='players_pla_ign_72ab0a_idx',
        ),
    ]
