# Generated by Django 5.2.7 on 2025-10-24 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_remove_player_players_pla_ign_72ab0a_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ign',
            field=models.CharField(help_text="Player's in-game name (2-24 characters: letters, numbers, underscores, hyphens, periods)", max_length=24, unique=True, validators=[django.core.validators.RegexValidator(message='In-Game Name must be 2-24 characters long and can include letters, numbers, underscores, hyphens, and periods.', regex='^[A-Za-z0-9_.\\-]{2,24}$')]),
        ),
    ]
