# Generated by Django 5.2.7 on 2025-10-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_alter_player_ign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ign',
            field=models.CharField(help_text="Player's in-game name (2-24 characters: letters, numbers, underscores, hyphens, periods)", max_length=24, unique=True),
        ),
    ]
