# Generated by Django 5.2.7 on 2025-10-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_alter_player_ign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ign',
            field=models.CharField(db_index=True, help_text='In-Game Name (IGN) of the player', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='playermembership',
            name='role_at_team',
            field=models.CharField(choices=[('GOLD', 'Gold Lane'), ('MID', 'Mid Lane'), ('JUNGLE', 'Jungle'), ('EXP', 'Exp Lane'), ('ROAM', 'Roam')], db_index=True, help_text="Player's primary role while at the team", max_length=10),
        ),
    ]
