# Generated by Django 5.2.7 on 2025-10-15 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('short_name', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Short name must be 2-10 characters long, containing only uppercase letters and numbers.', regex='^[A-Z0-9]{2,10}$'), django.core.validators.MinLengthValidator(2)])),
                ('region', models.CharField(choices=[('NA', 'North America'), ('ID', 'Indonesia'), ('MY', 'Malaysia'), ('PH', 'Philippines'), ('SG', 'Singapore'), ('BR', 'Brazil'), ('VN', 'Vietnam'), ('MM', 'Myanmar'), ('TH', 'Thailand'), ('IN', 'India'), ('TR', 'Turkey'), ('EU', 'Europe'), ('KR', 'Korea'), ('TW', 'Taiwan'), ('HK', 'Hong Kong'), ('JP', 'Japan'), ('CN', 'China'), ('MENA', 'Middle East and North Africa'), ('LATAM', 'Latin America'), ('INTL', 'International'), ('WORLD', 'World')], max_length=5)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('achievements', models.TextField(blank=True)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('social_media_links', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['-founded_year', 'name'],
                'indexes': [models.Index(fields=['region'], name='teams_team_region_4e12d6_idx'), models.Index(fields=['is_active'], name='teams_team_is_acti_6dafc6_idx'), models.Index(fields=['founded_year'], name='teams_team_founded_6c6a74_idx'), models.Index(fields=['region', 'is_active'], name='teams_team_region_ad7602_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('slug', ''), _negated=True), name='team_slug_not_empty'), models.CheckConstraint(condition=models.Q(('founded_year__isnull', True), models.Q(('founded_year__gte', 1850), ('founded_year__lte', 2100)), _connector='OR'), name='founded_year_valid_range')],
            },
        ),
    ]
