# Generated by Django 5.2.7 on 2025-10-19 03:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['short_name']},
        ),
        migrations.RemoveConstraint(
            model_name='team',
            name='founded_year_valid_range',
        ),
        migrations.RemoveIndex(
            model_name='team',
            name='teams_team_region_4e12d6_idx',
        ),
        migrations.RemoveField(
            model_name='team',
            name='social_media_links',
        ),
        migrations.AddField(
            model_name='team',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='team',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='x',
            field=models.URLField(blank=True, verbose_name='Twitter URL'),
        ),
        migrations.AddField(
            model_name='team',
            name='youtube',
            field=models.URLField(blank=True, verbose_name='YouTube URL'),
        ),
        migrations.AlterField(
            model_name='team',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1850), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='team',
            name='region',
            field=models.CharField(choices=[('NA', 'North America'), ('ID', 'Indonesia'), ('MY', 'Malaysia'), ('PH', 'Philippines'), ('SG', 'Singapore'), ('BR', 'Brazil'), ('VN', 'Vietnam'), ('MM', 'Myanmar'), ('TH', 'Thailand'), ('IN', 'India'), ('TR', 'Turkey'), ('EU', 'Europe'), ('KR', 'Korea'), ('TW', 'Taiwan'), ('HK', 'Hong Kong'), ('JP', 'Japan'), ('CN', 'China'), ('MENA', 'Middle East and North Africa'), ('LATAM', 'Latin America')], max_length=5),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('founded_year__gte', 1850), ('founded_year__lte', 2100)), ('founded_year__isnull', True), _connector='OR'), name='founded_year_valid_range'),
        ),
    ]
