# Generated by Django 5.2.7 on 2025-10-24 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_region'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='team',
            name='teams_team_is_acti_6dafc6_idx',
        ),
        migrations.RemoveIndex(
            model_name='team',
            name='teams_team_founded_6c6a74_idx',
        ),
    ]
