# Generated by Django 5.2.7 on 2025-10-24 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_remove_team_teams_team_is_acti_6dafc6_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='team',
            name='team_slug_not_empty',
        ),
        migrations.AlterField(
            model_name='team',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year the team was founded (between 1850 and 2100).', null=True, validators=[django.core.validators.MinValueValidator(1850), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='team',
            name='short_name',
            field=models.CharField(db_index=True, help_text='Abbreviated team name (2-10 uppercase letters/numbers).', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Short name must be 2-10 characters long, containing only uppercase letters and numbers.', regex='^[A-Z0-9]{2,10}$'), django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('short_name',), name='unique_team_short_name_ci_unique'),
        ),
    ]
