# Generated by Django 5.2.7 on 2025-10-26 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_remove_team_team_slug_not_empty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='region',
            field=models.CharField(choices=[('NA', 'North America'), ('ID', 'Indonesia'), ('MY', 'Malaysia'), ('PH', 'Philippines'), ('SG', 'Singapore'), ('BR', 'Brazil'), ('VN', 'Vietnam'), ('MM', 'Myanmar'), ('TH', 'Thailand'), ('IN', 'India'), ('TR', 'Turkey'), ('EU', 'Europe'), ('JP', 'Japan'), ('CN', 'China'), ('MENA', 'Middle East and North Africa'), ('KR', 'Korea'), ('TW', 'Taiwan'), ('HK', 'Hong Kong'), ('LATAM', 'Latin America'), ('INTL', 'International')], db_index=True, help_text='Select the region the team belongs to.', max_length=5),
        ),
        migrations.AlterField(
            model_name='team',
            name='short_name',
            field=models.CharField(db_index=True, help_text='Abbreviated team name (2-10 uppercase letters/numbers).', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Team short name must be 3-5 alphanumeric characters.', regex='^[A-Za-z0-9]{3,5}$'), django.core.validators.MinLengthValidator(2)]),
        ),
    ]
