# Generated by Django 5.2.7 on 2025-10-24 16:22

import apps.staff.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0006_remove_team_team_slug_not_empty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('handle', models.CharField(help_text='Public alias / coach tag (e.g. BONCHAN, MASTERCOACH).', max_length=24, unique=True, validators=[django.core.validators.RegexValidator(message='Handle must be 2–24 characters and can include letters, numbers, underscores, hyphens, and periods.', regex='^[A-Za-z0-9_\\-.]{2,24}$')])),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.staff.models.staff_photo_upload_to)),
                ('primary_role', models.CharField(choices=[('HEAD_COACH', 'Head Coach'), ('ASST_COACH', 'Assistant Coach'), ('ANALYST', 'Analyst'), ('MANAGER', 'Team Manager')], db_index=True, help_text='Main role overall (head coach, analyst, etc.)', max_length=20)),
                ('nationality', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 code (e.g. PH)', max_length=2)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Is this staff member still active in the scene?')),
                ('bio', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('x', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['handle'],
                'indexes': [models.Index(fields=['primary_role', 'is_active'], name='staff_staff_primary_13dcf9_idx'), models.Index(fields=['nationality'], name='staff_staff_nationa_c3ca64_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('slug', ''), _negated=True), name='staff_slug_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='StaffMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_at_team', models.CharField(choices=[('HEAD_COACH', 'Head Coach'), ('ASST_COACH', 'Assistant Coach'), ('ANALYST', 'Analyst'), ('MANAGER', 'Team Manager')], db_index=True, help_text='Role held on this specific team during this period.', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if still active with this team.', null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='staff.staff')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_memberships', to='teams.team')),
            ],
            options={
                'ordering': ('-start_date',),
                'indexes': [models.Index(fields=['team', 'start_date'], name='staff_staff_team_id_6cfebd_idx'), models.Index(fields=['staff', 'start_date'], name='staff_staff_staff_i_8ad754_idx')],
                'unique_together': {('staff', 'team', 'start_date')},
            },
        ),
    ]
