# Generated by Django 5.2.7 on 2025-10-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='handle',
            field=models.CharField(db_index=True, help_text='Public alias / coach tag (e.g. BONCHAN, MASTERCOACH).', max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='nationality',
            field=models.CharField(blank=True, db_index=True, help_text='ISO 3166-1 alpha-2 code (e.g. PH)', max_length=2),
        ),
    ]
