# Generated by Django 5.2.7 on 2025-10-19 07:04

import heroes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_hero_hero_pic'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hero',
            name='heroes_hero_hero_cl_345489_idx',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='hero_class',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='hero_pic',
        ),
        migrations.AddField(
            model_name='hero',
            name='hero_icon',
            field=models.ImageField(blank=True, null=True, upload_to=heroes.models.hero_icon_upload_to),
        ),
        migrations.AddField(
            model_name='hero',
            name='primary_class',
            field=models.CharField(choices=[('TANK', 'Tank'), ('FIGHTER', 'Fighter'), ('ASSASSIN', 'Assassin'), ('MAGE', 'Mage'), ('MARKSMAN', 'Marksman'), ('SUPPORT', 'Support')], db_index=True, default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='secondary_class',
            field=models.CharField(blank=True, choices=[('TANK', 'Tank'), ('FIGHTER', 'Fighter'), ('ASSASSIN', 'Assassin'), ('MAGE', 'Mage'), ('MARKSMAN', 'Marksman'), ('SUPPORT', 'Support')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='hero',
            index=models.Index(fields=['primary_class'], name='heroes_hero_primary_196735_idx'),
        ),
    ]
