# Generated by Django 5.2.7 on 2025-10-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='rules',
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_rules_link',
            field=models.URLField(blank=True, help_text='Link to the tournament rules'),
        ),
    ]
