# Generated by Django 5.2.7 on 2025-10-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_remove_tournament_rules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='tier',
            field=models.CharField(choices=[('S', 'S-tier'), ('A', 'A-tier'), ('B', 'B-tier'), ('C', 'C-tier'), ('D', 'D-tier')], db_index=True, default=1, max_length=2),
            preserve_default=False,
        ),
    ]
