# Generated by Django 5.2.7 on 2025-10-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_remove_stage_unique_stage_name_per_tournament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], db_index=True, default=1, max_length=10),
            preserve_default=False,
        ),
    ]
