# Generated by Django 5.2.7 on 2025-10-17 12:35

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_stage_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('tournament', 'order'), name='unique_stage_order_per_tournament'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1)), name='stage_order_gte_1'),
        ),
    ]
