# Generated by Django 5.2.7 on 2025-10-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_stage_unique_stage_order_per_tournament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='tier',
            field=models.CharField(choices=[('1', 'Tier 1'), ('2', 'Tier 2'), ('3', 'Tier 3'), ('4', 'Tier 4'), ('5', 'Tier 5')], db_index=True, max_length=2),
        ),
    ]
