# Generated by Django 5.2.7 on 2025-10-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_alter_stage_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
    ]
