# Generated by Django 5.2.7 on 2025-10-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_alter_stage_end_date_alter_stage_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='stage_type',
            field=models.CharField(choices=[('WILD CARD', 'Wild Card Stage'), ('GROUPS', 'Group Stage'), ('REGULAR SEASON', 'Regular Season'), ('KNOCKOUTS', 'Knockout Stage'), ('PLAYOFFS', 'Playoff Stage'), ('FINALS', 'Grand Finals')], db_index=True, max_length=20),
        ),
    ]
