# Generated by Django 5.2.7 on 2025-10-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_remove_series_unique_series_per_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='region',
            field=models.CharField(choices=[('NA', 'North America'), ('ID', 'Indonesia'), ('MY', 'Malaysia'), ('PH', 'Philippines'), ('SG', 'Singapore'), ('BR', 'Brazil'), ('VN', 'Vietnam'), ('MM', 'Myanmar'), ('TH', 'Thailand'), ('IN', 'India'), ('TR', 'Turkey'), ('EU', 'Europe'), ('KR', 'Korea'), ('TW', 'Taiwan'), ('HK', 'Hong Kong'), ('JP', 'Japan'), ('CN', 'China'), ('MENA', 'Middle East and North Africa'), ('LATAM', 'Latin America')], max_length=5),
        ),
    ]
