# Generated by Django 5.2.7 on 2025-10-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_tournamentteam_and_more'),
        ('teams', '0003_alter_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamgamestat',
            name='gold',
            field=models.PositiveIntegerField(default=0, help_text='Total Gold Earned by the team'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(blank=True, help_text='Teams participating in the tournament', related_name='tournaments', through='competitions.TournamentTeam', to='teams.team'),
        ),
    ]
