# Generated by Django 5.2.7 on 2025-10-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0015_alter_tournament_region'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stage',
            name='competition_tournam_4ec9ab_idx',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='name',
        ),
        migrations.AddField(
            model_name='stage',
            name='variant',
            field=models.CharField(blank=True, help_text="Variant of the stage, e.g., 'Double Elimination'", max_length=50),
        ),
        migrations.AlterField(
            model_name='stage',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='stage',
            index=models.Index(fields=['tournament', 'stage_type'], name='competition_tournam_5057f3_idx'),
        ),
    ]
