# Generated by Django 5.2.7 on 2025-10-20 09:41

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0016_remove_stage_competition_tournam_4ec9ab_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stage',
            name='unique_stage_type_per_tournament',
        ),
        migrations.RemoveIndex(
            model_name='stage',
            name='competition_tournam_5057f3_idx',
        ),
        migrations.AddIndex(
            model_name='stage',
            index=models.Index(fields=['tournament', 'stage_type', 'variant'], name='competition_tournam_027dac_idx'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('tournament', 'stage_type', 'variant'), name='unique_stage_type_variant_per_tournament'),
        ),
    ]
