# Generated by Django 5.2.7 on 2025-10-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0018_alter_game_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamgamestat',
            old_name='turret_destroyed',
            new_name='tower_destroyed',
        ),
        migrations.RemoveField(
            model_name='teamgamestat',
            name='a',
        ),
        migrations.RemoveField(
            model_name='teamgamestat',
            name='d',
        ),
        migrations.RemoveField(
            model_name='teamgamestat',
            name='first_blood',
        ),
        migrations.RemoveField(
            model_name='teamgamestat',
            name='game_win',
        ),
        migrations.RemoveField(
            model_name='teamgamestat',
            name='k',
        ),
        migrations.AddField(
            model_name='teamgamestat',
            name='game_result',
            field=models.CharField(choices=[('VICTORY', 'Win'), ('DEFEAT', 'Loss')], default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamgamestat',
            name='orange_buff',
            field=models.PositiveIntegerField(default=0, help_text='Number of Orange Buffs secured'),
        ),
        migrations.AddField(
            model_name='teamgamestat',
            name='purple_buff',
            field=models.PositiveIntegerField(default=0, help_text='Number of Purple Buffs secured'),
        ),
        migrations.AddField(
            model_name='teamgamestat',
            name='score',
            field=models.PositiveIntegerField(default=0, help_text='Total Team Score'),
        ),
    ]
