# Generated by Django 5.2.7 on 2025-10-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0019_rename_turret_destroyed_teamgamestat_tower_destroyed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergamestat',
            name='a',
            field=models.PositiveSmallIntegerField(default=0, help_text='Assists'),
        ),
        migrations.AlterField(
            model_name='playergamestat',
            name='d',
            field=models.PositiveSmallIntegerField(default=0, help_text='Deaths'),
        ),
        migrations.AlterField(
            model_name='playergamestat',
            name='k',
            field=models.PositiveSmallIntegerField(default=0, help_text='Kills'),
        ),
        migrations.AlterField(
            model_name='teamgamestat',
            name='game_result',
            field=models.CharField(choices=[('VICTORY', 'Win'), ('DEFEAT', 'Loss')], help_text='Result of the game for the team', max_length=7),
        ),
        migrations.AlterField(
            model_name='teamgamestat',
            name='lord_kills',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamgamestat',
            name='orange_buff',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of Orange Buffs secured'),
        ),
        migrations.AlterField(
            model_name='teamgamestat',
            name='purple_buff',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of Purple Buffs secured'),
        ),
        migrations.AlterField(
            model_name='teamgamestat',
            name='tower_destroyed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamgamestat',
            name='turtle_kills',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
