# Generated by Django 5.2.7 on 2025-10-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0020_alter_playergamestat_a_alter_playergamestat_d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamgamestat',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, help_text='Total Team Score'),
        ),
    ]
