# Generated by Django 5.2.7 on 2025-10-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0021_alter_teamgamestat_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedraftaction',
            name='side',
            field=models.CharField(choices=[('BLUE', 'Blue'), ('RED', 'Red')], db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='teamgamestat',
            name='side',
            field=models.CharField(choices=[('BLUE', 'Blue'), ('RED', 'Red')], db_index=True, max_length=5),
        ),
    ]
