# Generated by Django 5.2.7 on 2025-10-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0026_remove_game_competition_series__e34ac2_idx_and_more'),
        ('heroes', '0003_remove_hero_heroes_hero_hero_cl_345489_idx_and_more'),
        ('players', '0005_alter_player_ign'),
        ('teams', '0004_alter_team_region'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gamedraftaction',
            name='competition_game_id_9ba2e9_idx',
        ),
        migrations.RemoveIndex(
            model_name='gamedraftaction',
            name='competition_team_id_571ce8_idx',
        ),
        migrations.RemoveIndex(
            model_name='gamedraftaction',
            name='competition_side_2a26f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='gamedraftaction',
            name='competition_action_e467f4_idx',
        ),
        migrations.RemoveIndex(
            model_name='gamedraftaction',
            name='competition_hero_id_855368_idx',
        ),
        migrations.AddIndex(
            model_name='gamedraftaction',
            index=models.Index(fields=['game', 'side', 'order'], name='competition_game_id_f50510_idx'),
        ),
    ]
