# Generated by Django 5.2.7 on 2025-10-24 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0027_remove_gamedraftaction_competition_game_id_9ba2e9_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tournament',
            name='competition_start_d_4b1c3f_idx',
        ),
        migrations.RemoveIndex(
            model_name='tournament',
            name='competition_end_dat_8cd8c3_idx',
        ),
        migrations.RemoveIndex(
            model_name='tournament',
            name='competition_start_d_7cbdd6_idx',
        ),
    ]
