# Generated by Django 5.2.7 on 2025-10-25 14:38

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0029_alter_tournamentteam_options_and_more'),
        ('teams', '0006_remove_team_team_slug_not_empty_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='series',
            name='unique_series_per_stage_teams',
        ),
        migrations.AddConstraint(
            model_name='series',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('tournament', 'stage', 'team1', 'team2', 'scheduled_date'), name='unique_matchup_per_stage'),
        ),
    ]
