# Generated by Django 5.2.7 on 2025-10-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0030_remove_series_unique_series_per_stage_teams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='region',
            field=models.CharField(choices=[('NA', 'North America'), ('ID', 'Indonesia'), ('MY', 'Malaysia'), ('PH', 'Philippines'), ('SG', 'Singapore'), ('BR', 'Brazil'), ('VN', 'Vietnam'), ('MM', 'Myanmar'), ('TH', 'Thailand'), ('IN', 'India'), ('TR', 'Turkey'), ('EU', 'Europe'), ('JP', 'Japan'), ('CN', 'China'), ('MENA', 'Middle East and North Africa'), ('KR', 'Korea'), ('TW', 'Taiwan'), ('HK', 'Hong Kong'), ('LATAM', 'Latin America'), ('INTL', 'International')], db_index=True, help_text='Primary region or league this tournament belongs to (e.g. PH, ID, INTL).', max_length=8),
        ),
    ]
