# Generated by Django 5.2.7 on 2025-10-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0031_alter_tournament_region'),
        ('heroes', '0004_remove_hero_hero_slug_not_empty_and_more'),
        ('players', '0009_alter_player_ign_alter_playermembership_role_at_team'),
        ('teams', '0007_alter_team_region_alter_team_short_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playergamestat',
            name='valid_role_value',
        ),
        migrations.RemoveConstraint(
            model_name='tournament',
            name='end_date_after_start_date',
        ),
        migrations.RenameField(
            model_name='teamgamestat',
            old_name='score',
            new_name='t_score',
        ),
        migrations.AlterField(
            model_name='game',
            name='result_type',
            field=models.CharField(choices=[('NORMAL', 'Normal Win'), ('FORFEIT_TEAM1', 'Forfeit Team 1'), ('FORFEIT_TEAM2', 'Forfeit Team 2'), ('DRAW', 'Draw')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='gamedraftaction',
            name='side',
            field=models.CharField(choices=[('BLUE', 'Blue Side'), ('RED', 'Red Side')], db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='playergamestat',
            name='role',
            field=models.CharField(choices=[('GOLD', 'Gold Lane'), ('MID', 'Mid Lane'), ('JUNGLE', 'Jungle'), ('EXP', 'Exp Lane'), ('ROAM', 'Roam')], db_index=True, help_text='Role played in this match (Gold, Mid, Jungle, EXP, Roam)', max_length=10),
        ),
        migrations.AlterField(
            model_name='series',
            name='best_of',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Best of 1'), (3, 'Best of 3'), (5, 'Best of 5'), (7, 'Best of 7')], default=3, help_text='Length of the series (Bo3, Bo5...).', null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_type',
            field=models.CharField(choices=[('WILD CARD', 'Wild card Stage'), ('REGULAR SEASON', 'Regular Season'), ('KNOCKOUT', 'Knockout Stage'), ('GROUP', 'Group Stage'), ('PLAYOFFS', 'Playoff Stage'), ('FINALS', 'Finals')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='stage',
            name='tier',
            field=models.CharField(choices=[('T1', 'T1-tier'), ('T2', 'T2-tier'), ('T3', 'T3-tier'), ('T4', 'T4-tier'), ('T5', 'T5-tier'), ('T6', 'T6-tier')], db_index=True, help_text='Tier weight for ranking calc (1 = highest).', max_length=2),
        ),
        migrations.AlterField(
            model_name='teamgamestat',
            name='side',
            field=models.CharField(choices=[('BLUE', 'Blue Side'), ('RED', 'Red Side')], db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tier',
            field=models.CharField(choices=[('SS', 'SS-tier'), ('S', 'S-tier'), ('A', 'A-tier'), ('B', 'B-tier'), ('C', 'C-tier'), ('D', 'D-tier')], db_index=True, help_text='S-tier (world), A-tier (continental), B-tier (franchise league), etc.', max_length=5),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='kind',
            field=models.CharField(blank=True, choices=[('INVITED', 'Invited'), ('QUALIFIED', 'Qualified'), ('WILDCARD', 'Wild Card'), ('FRANCHISE', 'Franchise')], help_text='How this team qualified (Invited / Qualified / Franchise).', max_length=12),
        ),
        migrations.AddIndex(
            model_name='playergamestat',
            index=models.Index(fields=['role'], name='competition_role_d1f7e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='tournament_end_after_start'),
        ),
    ]
