# Generated by Django 5.2.7 on 2025-10-17 12:06

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_stage_tier'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stage',
            name='unique_stage_name_per_tournament',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='name',
        ),
        migrations.AddField(
            model_name='stage',
            name='stage_type',
            field=models.CharField(choices=[('WILD_CARDS', 'Wild Card Stage'), ('GROUPS', 'Group Stage'), ('REGULAR_SEASON', 'Regular Season'), ('KNOCKOUTS', 'Knockout Stage'), ('PLAYOFFS', 'Playoff Stage'), ('FINALS', 'Grand Finals')], db_index=True, default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['start_date', 'end_date'], name='competition_start_d_7cbdd6_idx'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('tournament', 'stage_type'), name='unique_stage_type_per_tournament'),
        ),
    ]
