# Generated by Django 5.2.7 on 2025-10-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0013_alter_teamgamestat_gold_alter_tournament_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='stage_type',
            field=models.CharField(choices=[('WILD CARD', 'Wild Card Stage'), ('GROUPS', 'Group Stage'), ('REGULAR SEASON', 'Regular Season'), ('KNOCKOUTS', 'Knockout Stage'), ('PLAYOFFS', 'Playoffs Stage'), ('FINALS', 'Grand Finals')], db_index=True, max_length=20),
        ),
    ]
