# Generated by Django 5.2.7 on 2025-10-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_remove_stage_unique_stage_type_per_tournament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='duration',
            field=models.DurationField(blank=True, help_text='Duration of the game', null=True),
        ),
    ]
