# Generated by Django 5.2.7 on 2025-10-22 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0025_remove_teamgamestat_competition_game_id_6e7c1f_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='game',
            name='competition_series__e34ac2_idx',
        ),
        migrations.RemoveIndex(
            model_name='game',
            name='competition_blue_si_a6f754_idx',
        ),
        migrations.RemoveIndex(
            model_name='game',
            name='competition_red_sid_1b36d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='game',
            name='competition_winner__565661_idx',
        ),
        migrations.RemoveIndex(
            model_name='game',
            name='competition_game_no_c8af2c_idx',
        ),
        migrations.RemoveIndex(
            model_name='playergamestat',
            name='competition_game_id_5d66e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='playergamestat',
            name='competition_player__3c9501_idx',
        ),
        migrations.RemoveIndex(
            model_name='playergamestat',
            name='competition_team_id_93492a_idx',
        ),
        migrations.RemoveIndex(
            model_name='playergamestat',
            name='competition_role_d1f7e8_idx',
        ),
        migrations.RemoveIndex(
            model_name='playergamestat',
            name='competition_game_id_9104c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='playergamestat',
            name='competition_team_id_1e132a_idx',
        ),
    ]
